### ISSUE TITLE
Terasology Feedback

### ISSUE THREAD

**Issue by crossingthesarchasm** [RPG-Research/bcirpg#11]
Leave feedback for Terasology below

**Comment by PersonGuyGit** [comment]
Pros:

- Feature complete to older editions of Minecraft. 

- Good graphics with particle effects, god rays, shadows, etc

- Really fun compared to classic cube

Cons:

- It has it's own launcher, in the age of the PC Game Launcher Pandemic

- Not as easy to run as Classic Cube, but it does run good on my hardware

**Comment by d-zilla** [comment]
Pros:
* Rich color
* Realistic map features

Cons:
* Too bulky; too many settings
* No crafting, at all?

**Comment by crossingthesarchasm** [comment]
Feedback period closed
