### ISSUE TITLE
Truecraft Feedback

### ISSUE THREAD

**Issue by crossingthesarchasm** [RPG-Research/bcirpg#13]
Leave feedback for truecraft below

**Comment by PersonGuyGit** [comment]
Con so far (7.11.2020)

It must be compiled and ported to an EXE by the user, this is a bad UX.

Got this error upon compile
========== Build: 2 succeeded, 3 failed, 0 up-to-date, 0 skipped ==========

Requires the Mono core, seems like a bit much to me.

**Comment by crossingthesarchasm** [comment]
Feedback period closed
