### ISSUE TITLE
Classicube Feedback

### ISSUE THREAD

**Issue by crossingthesarchasm** [RPG-Research/bcirpg#16]
Leave feedback for classicube below

**Comment by PersonGuyGit** [comment]
Pros: 
- Lightweight, (Runs at high frame rates (I got 143 fps), 

- Crossplatform

- Nearly the same graphics as Mojang's Minecraft

- Good gameplay and controls

Cons: 
- Seems a bit limited compared to the Java/Bedrock editions imo.

- No animation for the TNT block during it's explode event; it just removes a large chunk of blocks.

**Comment by rpgresearch** [comment]
On Sat, 11 Jul 2020 11:29:07 -0700
Luke Gebbink <notifications@github.com> wrote:

> Pros: 
> - Lightweight, (Runs at high frame rates (I got 143 fps), 
> 
> - Crossplatform
> 
> - Nearly the same graphics as Mojang's Minecraft
> 
> - Good gameplay and controls
> 
> Cons: 
> - Seems a bit limited compared to the Java/Bedrock editions imo.
> 
> - No animation for the TNT block during it's explode event; it just
> removes a large chunk of blocks.
> 


Were you evaluating just the web client (which is reduced features), or
the installed client which has far more features supposedly?

-- 
--RPG Research Staff

RPG Research is a 501(c)3 non-profit charitable organization providing
research and community services. https://www.rpgresearch.com
info@rpgresearch.com
1312 North Monroe, Suite #114
Spokane, Washington 99218, US.
Spokane Local Number: (509) 608-7630
Toll-free: (833) RPG-INFO (774-4636)

**Comment by PersonGuyGit** [comment]
The installed client. Did not get a chance yet to try any of the web based clients for the minecraft clones

**Comment by crossingthesarchasm** [comment]
Feedback period closed
