### ISSUE TITLE
Move erpg Private Repo into the RPG Research Organization

### ISSUE THREAD

**Issue by sissieadmin** [RPG-Research/bcirpg#21]
There is an RPG Research Organization now, and this repo may be more appropriately moved under that Organization.

I will add the relevant team members to that organization, but the move must be done from with the rpgresearch account since the repo is owned by that user.

**Comment by rpgresearch** [comment]
On Wed, 25 Nov 2020 15:32:38 -0800
Niklas Anderson <notifications@github.com> wrote:

> There is an RPG Research Organization now, and this repo may be more
> appropriately moved under that Organization.
> 
> I will add the relevant team members to that organization, but the
> move must be done from with the rpgresearch account since the repo is
> owned by that user.
> 

You should have a message asking to confirm transfer now.

-- 
--RPG Research Staff

RPG Research is a 501(c)3 non-profit charitable organization providing
research and community services. https://www.rpgresearch.com
info@rpgresearch.com
1312 North Monroe, Suite #114
Spokane, Washington 99218, US.
Spokane Local Number: (509) 608-7630
Toll-free: (833) RPG-INFO (774-4636)

**Comment by crossingthesarchasm** [comment]
Transfer confirmed; repository now under RPG Research
