### ISSUE TITLE
Load Game function, when main menu "button" selected, invoke Load Game menu and dispose of Main Menu. Make Load Game menu the focus.

### ISSUE THREAD

**Issue by rpghawke** [RPG-Research/bcirpg#28]

**Comment by crossingthesarchasm** [comment]
@MacDugRPG I believe this is finished/integrated in the current game. Please confirm and close if you agree

**Comment by MacDugRPG** [comment]
Load game was implemented into the demo code in one of the prior versions, but the method of saving and loading the game was temporary and won't reflect the game made by the toolset. I think this specific issue can be closed; this will need to be implemented with the toolset generated game code and our actual process for saving and loading games across the various formats.
