### ISSUE TITLE
Create Player Character function. When Create Player Character "button" selected, invoke the Create PC menu and dispose of main menu, making PC menu the active interface.

### ISSUE THREAD

**Issue by rpghawke** [RPG-Research/bcirpg#30]

**Comment by crossingthesarchasm** [comment]
@MacDugRPG I believe this is finished/integrated in the current game, though I don't think the actual character creation is fully fleshed out. Please let me know if you agree -- we can close this and create a separate issue for character creation

**Comment by MacDugRPG** [comment]
The create PC process was not fully completed for the game code, only so far as generating output files and loading temporary/set values into the game. These values could also be used to check against/modify die rolls, for example, but this will function differently in the actual game that's generated by the toolset, so this may be closed.
