### ISSUE TITLE
G9 Tutorial Island Issues

### ISSUE THREAD

**Issue by DevTimmo** [RPG-Research/bcirpg#4]
@TrevorSTroxel 

## G9 Tutorial

- Trinculo says "Come talk to me!" twice at launch
    - [
![image](https://user-images.githubusercontent.com/36526816/85087071-6da04c80-b1aa-11ea-98f9-5300cae4205f.png)
](url)
- Trinculo conversation typo
    - "Try talking to **Sebastian**, he may know a thing or two, or **Stephano** if you want to move on."
- Stephano conversation typo
   - "I see. Why don't you take that door behind you to go to the top of the **deck**

- After using the door to exit the tutorial maybe make the waypoint off of the area trigger to return to the previous zone.
    - Upon further testing, this area trigger appears to not work. If we are not supposed to return to the tutorial should there be an area trigger here?

**Comment by crossingthesarchasm** [comment]
Overall module closed and completed -- in project repository under Phase 1
