### ISSUE TITLE
Database Setup.

### ISSUE THREAD

**Issue by PersonGuyGit** [RPG-Research/bcirpg#46]
To use SQLite with Godot, you will need to get a few things.

First, you need the GodotSQLite plugin made by 2Shady4U. And you will also need the DBBrowser For SQLite.

Instructions on the basic Database setup and workflow are found in this video: https://www.youtube.com/watch?v=HG-PV4rlzoY

If you are on Linux, it is much easier to download DBBrowser from your package store (Such as Add and Remove software on Manjaro)

**Comment by rpgresearch** [comment]
Will we be allowed to just bundle SQLite with our game so that end users don't have to manually install SQLite themselves? @PersonGuyGit

**Comment by crossingthesarchasm** [comment]
@PersonGuyGit Has this been resolved? Please close if so, otherwise please update in the comments

**Comment by PersonGuyGit** [comment]
We are no longer working with SQLite, so this issue can be disregarded.
