### ISSUE TITLE
Game Code: Resolve warnings and errors in output

### ISSUE THREAD

**Issue by MacDugRPG** [RPG-Research/bcirpg#48]
Current game code has a series of errors and warnings that are output during execution -- these need to be resolved. Example:

ERROR: ~List: Condition "_first != __null" is true.
   At: ./core/self_list.h:112
ERROR: ~List: Condition "_first != __null" is true.
   At: ./core/self_list.h:112
WARNING: cleanup: ObjectDB instances leaked at exit (run with --verbose for details).
     At: core/object.cpp:2132
ERROR: clear: Resources still in use at exit (run with --verbose for details).
   At: core/resource.cpp:450

**Comment by crossingthesarchasm** [comment]
@MacDugRPG I believe this was resolved, please close if so

**Comment by MacDugRPG** [comment]
These issues were resolved during the web-based updates to the game code.
